spring.application.name=market
# this line was causing problems...do I need it and what does it do???
# management spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

spring.datasource.url=jdbc:mysql://localhost:3307/marketdb
spring.datasource.username=user
spring.datasource.password=Mu4ph7&L1nk2107

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
